use i_triangle::float::relax::{RelaxationOptions, RelaxationResult};
use i_triangle::float::triangulation::Triangulation;
use i_triangle::float::uniform::UniformTriangulatable;
use i_triangle::i_overlay::core::fill_rule::FillRule;
use i_triangle::i_overlay::core::overlay_rule::OverlayRule;
use i_triangle::i_overlay::float::single::SingleFloatOverlay;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

type Point = [f64; 2];

const EDGE_LENGTH: f64 = 3.5;
const RELAX_ITERATIONS: usize = 24;
const VIEW_BOX: &str = "0 0 132.29167 67.97879";

fn main() -> io::Result<()> {
    let contours: Vec<Vec<Point>> = EAGLE_CONTOURS
        .iter()
        .map(|contour| contour.to_vec())
        .collect();
    let empty: Vec<Vec<Point>> = Vec::new();
    let shapes = contours.overlay(&empty, OverlayRule::Union, FillRule::EvenOdd);
    assert_eq!(shapes.len(), 1, "the eagle must normalize to one shape");

    let shape = &shapes[0];
    let mut delaunay = shape.uniform_triangulate(EDGE_LENGTH);
    let relaxation = delaunay.relax_mut(RelaxationOptions::new(RELAX_ITERATIONS));
    let centroid_net = delaunay.to_centroid_net(0.0);
    let triangulation = delaunay.to_triangulation::<u32>();

    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("readme");
    fs::write(
        root.join("eagle_tessellation.svg"),
        tessellation_svg(shape, &triangulation, relaxation),
    )?;
    fs::write(
        root.join("eagle_centroid.svg"),
        centroid_svg(shape, &centroid_net, relaxation),
    )?;

    println!(
        "generated: {} points, {} triangles, {} centroid cells, relax={:?}",
        triangulation.points.len(),
        triangulation.indices.len() / 3,
        centroid_net.len(),
        relaxation
    );
    Ok(())
}

fn tessellation_svg(
    shape: &[Vec<Point>],
    triangulation: &Triangulation<Point, u32>,
    relaxation: RelaxationResult,
) -> String {
    let mut svg = svg_header(
        "Relaxed uniform Delaunay tessellation",
        relaxation,
        triangulation.points.len(),
    );
    append_shape_fill(&mut svg, shape);

    let mut edges = BTreeSet::new();
    for triangle in triangulation.indices.chunks_exact(3) {
        for (a, b) in [
            (triangle[0], triangle[1]),
            (triangle[1], triangle[2]),
            (triangle[2], triangle[0]),
        ] {
            edges.insert(if a < b { (a, b) } else { (b, a) });
        }
    }

    svg.push_str("  <path d=\"");
    for (a, b) in edges {
        append_segment(
            &mut svg,
            triangulation.points[a as usize],
            triangulation.points[b as usize],
        );
    }
    svg.push_str(
        "\" fill=\"none\" stroke=\"#3f4850\" stroke-width=\"0.13\" \
         stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n",
    );
    append_shape_outline(&mut svg, shape);
    svg.push_str("</svg>\n");
    svg
}

fn centroid_svg(
    shape: &[Vec<Point>],
    centroid_net: &[Vec<Point>],
    relaxation: RelaxationResult,
) -> String {
    let mut svg = svg_header(
        "Centroid net of a relaxed uniform Delaunay mesh",
        relaxation,
        centroid_net.len(),
    );
    append_shape_fill(&mut svg, shape);

    svg.push_str("  <path d=\"");
    append_contours(&mut svg, centroid_net);
    svg.push_str(
        "\" fill=\"none\" stroke=\"#3f4850\" stroke-width=\"0.14\" \
         stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n",
    );
    append_shape_outline(&mut svg, shape);
    svg.push_str("</svg>\n");
    svg
}

fn svg_header(title: &str, relaxation: RelaxationResult, element_count: usize) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"500\" height=\"257\" \
         viewBox=\"{VIEW_BOX}\" shape-rendering=\"geometricPrecision\">\n\
         <!-- Generated by cargo example: eagle_svg -->\n\
         <!-- edge_length={EDGE_LENGTH}, relax_iterations={}, converged={}, elements={} -->\n\
           <title>{title}</title>\n",
        relaxation.iterations, relaxation.converged, element_count
    )
}

fn append_shape_fill(svg: &mut String, shape: &[Vec<Point>]) {
    svg.push_str("  <path d=\"");
    append_contours(svg, shape);
    svg.push_str("\" fill=\"#eceff1\" fill-rule=\"evenodd\" stroke=\"none\"/>\n");
}

fn append_shape_outline(svg: &mut String, shape: &[Vec<Point>]) {
    svg.push_str("  <path d=\"");
    append_contours(svg, shape);
    svg.push_str(
        "\" fill=\"none\" stroke=\"#252b30\" stroke-width=\"0.42\" \
         stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n",
    );
}

fn append_contours(svg: &mut String, contours: &[Vec<Point>]) {
    for contour in contours {
        let Some(&first) = contour.first() else {
            continue;
        };
        append_move(svg, first);
        for &point in &contour[1..] {
            append_line(svg, point);
        }
        svg.push_str("Z\n    ");
    }
}

fn append_segment(svg: &mut String, a: Point, b: Point) {
    append_move(svg, a);
    append_line(svg, b);
    svg.push_str("\n    ");
}

fn append_move(svg: &mut String, point: Point) {
    write!(svg, "M{:.5},{:.5} ", point[0], point[1]).unwrap();
}

fn append_line(svg: &mut String, point: Point) {
    write!(svg, "L{:.5},{:.5}", point[0], point[1]).unwrap();
}

// Extracted once from the compound silhouette path in the historical SVG.
// The first contour is the eagle outline; the remaining contours are holes.
const EAGLE_CONTOURS: &[&[Point]] = &[
    &[
        [12.64125100, 0.21080764],
        [12.64125100, 5.59553420],
        [14.26289800, 9.36515110],
        [16.42475200, 11.51914500],
        [12.91135400, 10.71133300],
        [9.39847060, 9.90352090],
        [5.34538210, 8.28789720],
        [1.29177810, 6.67278770],
        [3.99435250, 9.63407880],
        [8.31754400, 13.67313800],
        [11.02011900, 14.21150700],
        [6.69641170, 14.74987700],
        [0.21085147, 14.74987700],
        [2.91342590, 17.98112400],
        [8.31754400, 19.05786400],
        [1.83249920, 20.67348800],
        [5.07527910, 22.82748000],
        [10.47939800, 22.82748000],
        [5.61548470, 24.98147400],
        [9.39847060, 26.59658400],
        [13.18197200, 26.59658400],
        [10.47939800, 28.75057700],
        [14.26289800, 29.28946000],
        [18.04588400, 28.75057700],
        [15.34382600, 30.90457100],
        [20.20773800, 31.44345500],
        [18.58609000, 33.05856400],
        [24.26082600, 32.52019500],
        [22.36959100, 36.28981200],
        [27.77370900, 35.21255700],
        [26.69329800, 37.90492000],
        [32.09741500, 36.28981200],
        [31.01649000, 38.98217400],
        [34.79999200, 37.36655000],
        [34.25926900, 40.59779800],
        [38.04225400, 38.98217400],
        [37.50205000, 41.67453700],
        [41.28503500, 39.52054300],
        [41.28503500, 42.75179100],
        [44.52781500, 40.59779800],
        [43.98761000, 43.82853000],
        [47.77059500, 41.67453700],
        [48.85152000, 39.52054300],
        [48.85152000, 43.29016100],
        [51.55358000, 41.13616700],
        [52.09430100, 39.52054300],
        [52.63450800, 42.75179100],
        [54.25615600, 41.67453700],
        [54.79636000, 40.05891300],
        [55.87728800, 42.75179100],
        [56.41749300, 46.52089500],
        [52.63450800, 48.40595900],
        [48.85152000, 50.29051200],
        [42.90668200, 50.82888200],
        [44.52781500, 54.06012700],
        [47.22987300, 54.59849800],
        [45.60874100, 55.67523700],
        [47.77059500, 57.82923100],
        [52.09430100, 58.36759900],
        [48.85152000, 59.44485500],
        [52.09430100, 62.13721700],
        [55.87728800, 61.59884700],
        [53.71543300, 63.75284100],
        [57.49842100, 65.36846500],
        [61.28192000, 64.82958200],
        [59.66027300, 67.52245800],
        [62.36284800, 67.52245800],
        [66.14583300, 65.36846500],
        [69.92881800, 67.52245800],
        [72.63139300, 67.52245800],
        [71.00974600, 64.82958200],
        [74.79324600, 65.36846500],
        [78.57623300, 63.75284100],
        [76.41437800, 61.59884700],
        [80.19736600, 62.13721700],
        [83.44014600, 59.44485500],
        [80.19736600, 58.36759900],
        [84.52107200, 57.82923100],
        [86.68292600, 55.67523700],
        [85.06179300, 54.59849800],
        [87.76385100, 54.06012700],
        [89.38498500, 50.82888200],
        [83.44014600, 50.29051200],
        [79.65715900, 48.40595900],
        [75.87365900, 46.52089500],
        [76.41437800, 42.75179100],
        [77.49530600, 40.05891300],
        [78.03551100, 41.67453700],
        [79.65715900, 42.75179100],
        [80.19736600, 39.52054300],
        [80.73808700, 41.13616700],
        [83.44014600, 43.29016100],
        [83.44014600, 39.52054300],
        [84.52107200, 41.67453700],
        [88.30405600, 43.82853000],
        [87.76385100, 40.59779800],
        [91.00663200, 42.75179100],
        [91.00663200, 39.52054300],
        [94.78961700, 41.67453700],
        [94.24941200, 38.98217400],
        [98.03239700, 40.59779800],
        [97.49167500, 37.36655000],
        [101.27518000, 38.98217400],
        [100.19425000, 36.28981200],
        [105.59836000, 37.90492000],
        [104.51796000, 35.21255700],
        [109.92207000, 36.28981200],
        [108.03084000, 32.52019500],
        [113.70558000, 33.05856400],
        [112.08393000, 31.44345500],
        [116.94784000, 30.90457100],
        [114.24578000, 28.75057700],
        [118.02876000, 29.28946000],
        [121.81227000, 28.75057700],
        [119.10970000, 26.59658400],
        [122.89319000, 26.59658400],
        [126.67619000, 24.98147400],
        [121.81227000, 22.82748000],
        [127.21639000, 22.82748000],
        [130.45916000, 20.67348800],
        [123.97412000, 19.05786400],
        [129.37824000, 17.98112400],
        [132.08082000, 14.74987700],
        [125.59525000, 14.74987700],
        [121.27155000, 14.21150700],
        [123.97412000, 13.67313800],
        [128.29731000, 9.63407880],
        [130.99988000, 6.67278770],
        [126.94628000, 8.28789720],
        [122.89319000, 9.90352090],
        [119.38031000, 10.71133300],
        [115.86691000, 11.51914500],
        [118.02876000, 9.36515110],
        [119.65042000, 5.59553420],
        [119.65042000, 0.21080764],
        [116.94784000, 5.59553420],
        [110.46279000, 8.28789720],
        [103.97724000, 10.98026000],
        [106.67929000, 8.28789720],
        [106.67929000, 5.05716430],
        [104.51796000, 7.74952740],
        [99.65353000, 9.63407880],
        [94.78961700, 11.51914500],
        [91.36694000, 14.39096400],
        [87.85405900, 17.17331300],
        [84.43086400, 20.04513200],
        [81.00818800, 22.82748000],
        [77.49530600, 24.44259100],
        [74.25252700, 24.44259100],
        [71.55046800, 23.90422100],
        [69.38861400, 22.28859700],
        [66.14583300, 21.75022700],
        [62.90305300, 22.28859700],
        [60.74119900, 23.90422100],
        [58.03914000, 24.44259100],
        [54.79636000, 24.44259100],
        [51.28347900, 22.82748000],
        [47.86080200, 20.04513200],
        [44.43760800, 17.17331300],
        [40.92472600, 14.39096400],
        [37.50205000, 11.51914500],
        [32.63813700, 9.63407880],
        [27.77370900, 7.74952740],
        [25.61237100, 5.05716430],
        [25.61237100, 8.28789720],
        [28.31443100, 10.98026000],
        [21.82887000, 8.28789720],
        [15.34382600, 5.59553420],
    ],
    &[
        [62.90305300, 28.75057700],
        [64.52470100, 30.36620100],
        [63.98397900, 31.44345500],
        [62.90305300, 30.36620100],
    ],
    &[
        [69.38861400, 28.75057700],
        [69.38861400, 30.36620100],
        [68.30768700, 31.44345500],
        [67.76696600, 30.36620100],
    ],
    &[
        [66.14583300, 30.36620100],
        [67.22675900, 30.90457100],
        [67.76696600, 31.98182500],
        [68.30768700, 32.52019500],
        [70.46953900, 32.52019500],
        [68.30768700, 33.59693300],
        [67.22675900, 34.67418800],
        [66.14583300, 37.36655000],
        [65.06490800, 34.67418800],
        [63.98397900, 33.59693300],
        [61.82212700, 32.52019500],
        [63.98397900, 32.52019500],
        [64.52470100, 31.98182500],
        [65.06490800, 30.90457100],
    ],
];
